### ISSUE TITLE
Breaks without "dependencies" key on package.json

### ISSUE THREAD

**Issue by renatofdds** [jakoblind/js-import#1]
If there's not a "dependencies" key on "package.json"  `json-import` breaks because it expects it to create a hash table. It should support projects without it.
It would be great to add support for "devDependencies" with a custom variable too.

**Comment by jakoblind** [comment]
I have fixed handling of empty `dependencies` section.

About `devDependencies`: we could enabling it with a prefix argument (`C-u M-x js-import`). What do you think about that?

**Comment by renatofdds** [comment]
Thank you for the fix! 

About `devDependencies`: I think the most flexible solution would be another interactive function for `devDependencies` (thus bindable) and a `prefix-arg` for `js-import` which would **cause** it to call this new function. This function would show normal files **and** `devDependencies`, and **no** normal dependencies. The reason being is that there are projects which only use `devDependencies`, such as those which only export a webpack bundle, and there are times when you want to switch between the two.

**Comment by jakoblind** [comment]
I have created a new interactive function `js-import-dev` which imports from the `devDepencies` section instead of `dependencies` . I think this is the simplest thing now. Hope this is helpful!

**Comment by renatofdds** [comment]
Great! Thanks a lot!

-----Original Message-----
