### ISSUE TITLE
You are not in a project

### ISSUE THREAD

**Issue by juvasquezg** [jakoblind/js-import#4]
Hi,

When I call 

```js
  M-x js-import
```

I get 

**You are not in a project**

Thank you!!

**Comment by juvasquezg** [comment]
I need to use [projectile](https://github.com/bbatsov/projectile) ?

**Comment by jakoblind** [comment]
Yes its a dependency on projectile. I will close this issue. Feel free to open another one if you have any additional questions or comments!
